### DISCUSSION TITLE
Feature Request: Collection Environment Variable Interpolation

### DISCUSSION THREAD

**Discussion by janrito** [darrenburns/posting#11] [Ideas]
practices around API authentication, token handling, etc vary widely. It would be really useful to be able to interpolate an environmental variable in a collection file. E.g.

```sh
# file: .envrc
$API_TOKEN="super-secret-token"
```

```yaml
# file: api.posting.yaml
name: Make an API Request
method: POST
url: https://bad-api.org/api/v1/list
params:
  - name: apiKey
    value: $API_TOKEN
```
