### DISCUSSION TITLE
Inherit theme from terminal

### DISCUSSION THREAD

**Discussion by CuriousFurBytes** [darrenburns/posting#56] [Ideas]
Hi! I really enjoy this! It was in my to-do list to do something like this, but well, this one is exactly what I was going to build.
I'm just missing a way to set the theme based on the terminal, something similar to what happens when you use lazygit, for example - it uses the colors from your terminal, instead of defining the background and foreground colors.
Right now I use Catppuccin Frappe, for example, and all the themes are very far from that - understandably.

Thanks!

**Comment by darrenburns** [comment]
Hey! Sorry - this isn't possible and is a deliberate design decision by Textual, the framework underlying Posting.

The reason is if we inherit from the terminal, we're only using ANSI colours and we have no idea how they will render in the end - that happens at the terminal emulator level after Posting renders.

It means we can't do things like automatically ensuring text is readable, opacity effects, colour blending, and more.

A theme system will arrive soon - possibly this week. You'll be able to add your own easily.

**Reply by CuriousFurBytes** [reply]
Theme system works for me! Thank you for the kind reply!

**Reply by diegoulloao** [reply]
Waiting for this feature!

**Comment by darrenburns** [comment]
@lucasqueiroz @diegoulloao Initial theme support is now available in `1.9.0`.

https://github.com/darrenburns/posting/releases/tag/1.9.0

**Comment by darrenburns** [comment]
Claude 3.5 Sonnet gave a decent starting point for Catpuccin Frappe 😄 Might need tweaking ofc...

<img width="738" alt="image" src="https://github.com/user-attachments/assets/a9e2b305-bf54-4e19-bba0-c7d777545e42">


```yaml
name: catppuccin_frappe
primary: '#8caaee'
secondary: '#e5c890'
accent: '#f4b8e4'
background: '#303446'
surface: '#414559'
error: '#e78284'
warning: '#ef9f76'
success: '#a6d189'
panel: '#51576d'
dark: true

author: Catppuccin
description: Soothing pastel theme for the high-spirited!
homepage: https://github.com/catppuccin/catppuccin
```
