### DISCUSSION TITLE
Share Your Themes Here!

### DISCUSSION THREAD

**Discussion by darrenburns** [darrenburns/posting#60] [Show and tell]
With the release of the new theme system - I'd love to see what people create!

If you create a theme and want to share it with the world, post it in here :)

### How to share

Post a comment below, including **a screenshot** and a **yaml file containing the theme**.

### Official gallery

In the future, I plan on having an "official" gallery of sorts and it'll be easy to install themes from there using the CLI. I'll pick out some of the best or most popular themes and add them to that gallery when it's ready.

I'll start! This is "aurora":

![image](https://github.com/user-attachments/assets/81456cf4-e373-433d-8cf7-d7d02c59d91d)

```yaml
name: aurora
primary: '#4a90e2'
secondary: '#50e3c2'
accent: '#b8e986'
background: '#1c2331'
surface: '#2c3e50'
error: '#e74c3c'
warning: '#f39c12'
success: '#2ecc71'
panel: '#34495e'
dark: true

author: Darren Burns
description: An example theme.
homepage: https://github.com/darrenburns/posting
```

**Comment by joshdeese** [comment]
**Catppuccin Mocha**

<img width="1424" alt="image" src="https://github.com/user-attachments/assets/8fc9fefe-5879-4869-8fe8-1b3375ec821e">

```
name: Catppuccin Mocha
primary: '#cba6f7'
secondary: '#a6e3a1'
accent: '#94e2d5'
background: '#1e1e2e'
surface: '#45475a'
error: '#f38ba8'
success: '#74c7ec'
warning: '#f9e2af'

text_area:
  cursor: 'reverse'
  cursor_line: 'underline'
  selection: 'reverse'
  gutter: 'bold #b4befe'
  matched_bracket: 'black on #a6e3a1'
url:
  base: 'italic #94e2d5'
  protocol: 'bold #a6e3a1'
syntax:
  json_key: 'italic #94e2d5'
  json_number: '#cba6f7'
  json_string: '#94e2d5'
  json_boolean: '#94e2d5'
  json_null: 'underline #94e2d5'

author: Josh Deese
description: A soothing pastel theme for the high-spirited!
homepage: https://github.com/catppuccin/catppuccin
```

**Comment by arturovilla** [comment]
### I call it Posttie
![SS_IOhGB3sg_0109AM@2x](https://github.com/user-attachments/assets/1e7c8fb2-e9a7-47d2-bfac-6e6cfdc6af22)
![SS_jz4VbivH_1251AM@2x](https://github.com/user-attachments/assets/a0b475e9-5864-44f1-b3b4-3967e5d620d5)

```
name: Posttie
primary: '#f2d5cf'
secondary: '#a6e3a1'
accent: '#06f5c0'
background: '#000000'
surface: '#232634'
error: '#d20f39'
success: '#40a02b'
warning: '#fe640b'

text_area:
  cursor: 'reverse'
  cursor_line: 'underline bold #06f5c0'
  selection: 'reverse'
  gutter: '#ff008b'
  matched_bracket: 'black on #a6e3a1'
url:
  base: 'bold #4a78e6'
  protocol: 'bold #73dc8c'
  separator: 'bold #4a78e6'
syntax:
  json_key: '#fa9afa'
  json_number: '#8cb4cd'
  json_string: '#73dc8c'
  json_boolean: '#ffa24e'
  json_null: '#4a74de'
method:
  get: '#73dc8c'
  post: '#dbde52'
  put: '#ffa24e'
  delete: '#ff665b'
  patch: '#ffa24e'
  options: '#8cb4cd'
  head: '#73dc8c'
variable:
  resolved: 'bold #ffa24e'
  unresolved: 'dim #ffa24e'

author: Arturo Villalobos
description: Cool theme partially inspired by the HTTPie color scheme.
```

**Comment by Chirikumbrah** [comment]
### Base16 Default Dark (+ some NeoVim Habamax colors)
<img width="1558" alt="image" src="https://github.com/user-attachments/assets/8c0d71ad-98ca-4a20-bf25-005404aa084b" />

```yaml
name: base16-default-dark
primary: "#d8d8d8"
secondary: "#7cafc2"
accent: "#ba8baf"
background: "#181818"
surface: "#181818"
error: "#ab4642"
success: "#a1b56c"
warning: "#f7ca88"

text_area:
  cursor_line: "bold"
  matched_bracket: "#181818 on #ba8baf"
syntax:
  json_key: "#87afaf"
  json_number: "#d7875f"
  json_string: "#a1b56c"
  json_boolean: "#d7875f"
  json_null: "#5f8787"

author: Chirikumbrah
description: Based on Alacritty default theme and some NeoVim Habamax colors :)
homepage: https://github.com/Chirikumbrah/dotfiles

```

**Comment by jkuester** [comment]
## GNOME Dark

![image](https://github.com/user-attachments/assets/b7e7997e-8c7c-4eac-966b-5989d26d67fb)

```yaml
name: gnome-dark  # use this name in your config file
primary: '#12488b'  # buttons, fixed table columns
secondary: '#a2734c'  # method selector, some minor labels
accent: '#26a269'  # header text, scrollbars, cursors, focus highlights
background: '#1e1e1e' # background colors
surface: '#242424'  # panels, etc
error: '#c01c28'  # error messages
success: '#26a269'  # success messages
warning: '#a2734c'  # warning messages

syntax:
  json_key: '#7d8ac7'  # style json keys
  json_number: '#7d8ac7'  # style json numbers
  json_string: '#5bc8af'  # style json strings
  json_boolean: '#7d8ac7'  # style json booleans
  json_null: '#7d8ac7'  # style json null values

method:
  get: 'bold #2aa1b3'
  post: 'bold #26a269'
  put: 'bold #a2734c'
  delete: 'bold #c01c28'

author: jkuester
description: A dark theme based on GNOME's default terminal colors.
```

**Comment by elithper** [comment]
## Rosé Pine

![Rosé Pine theme](https://github.com/user-attachments/assets/6a15710e-3721-4a09-90af-a176a42f0f96)

```yaml
name: rose-pine
primary: '#e0def4'
secondary: '#908caa'
accent: '#908caa'
background: '#191724'
surface: '#1f1d2e'
error: '#eb6f92'
success: '#9ccfd8'
warning: '#f6c177'

text_area:
  cursor: 'reverse'
  selection: 'reverse'
url:
  base: 'italic #e0def4'
  protocol: 'bold #e0def4'
syntax:
  json_key: '#9ccfd8'
  json_number: '#f6c177'
  json_string: '#f6c177'
  json_boolean: '#ebbcba'
  json_null: '#eb6f92'
method:
  get: 'bold #c4a7e7'
  post: 'bold #9ccfd8'
  put: 'bold #f6c177'
  delete: 'bold #eb6f92'
  patch: 'bold #31748f'
  head: 'bold #ebbcba'
  options: 'bold #e0def4'
variable:
  resolved: 'bold #e0def4'
  unresolved: 'dim #e0def4'

author: Michael Howard
description: All natural pine, faux fur and a bit of soho vibes for the classy minimalist
homepage: https://github.com/elithper/posting
```

## Rosé Pine Moon

![Rosé Pine Moon theme](https://github.com/user-attachments/assets/48c8773c-50ec-4fe9-8ebf-473ad0625b60)

```yaml
name: rose-pine-moon
primary: '#e0def4'
secondary: '#908caa'
accent: '#908caa'
background: '#232136'
surface: '#2a273f'
error: '#eb6f92'
success: '#9ccfd8'
warning: '#f6c177'

text_area:
  cursor: 'reverse'
  selection: 'reverse'
url:
  base: 'italic #e0def4'
  protocol: 'bold #e0def4'
syntax:
  json_key: '#9ccfd8'
  json_number: '#f6c177'
  json_string: '#f6c177'
  json_boolean: '#ea9a97'
  json_null: '#eb6f92'
method:
  get: 'bold #c4a7e7'
  post: 'bold #9ccfd8'
  put: 'bold #f6c177'
  delete: 'bold #eb6f92'
  patch: 'bold #3e8fb0'
  head: 'bold #ea9a97'
  options: 'bold #e0def4'
variable:
  resolved: 'bold #e0def4'
  unresolved: 'dim #e0def4'

author: Michael Howard
description: All natural pine, faux fur and a bit of soho vibes for the classy minimalist
homepage: https://github.com/elithper/posting
```

## Rosé Pine Dawn

![Rosé Pine Dawn theme](https://github.com/user-attachments/assets/22f307eb-3af9-4885-b0dc-ec277a02b8a6)

```yaml
name: rose-pine-dawn
primary: '#575279'
secondary: '#797593'
accent: '#797593'
background: '#faf4ed'
surface: '#fffaf3'
error: '#b4637a'
success: '#56949f'
warning: '#ea9d34'

text_area:
  cursor: 'reverse'
  selection: 'reverse'
url:
  base: 'italic #575279'
  protocol: 'bold #575279'
syntax:
  json_key: '#56949f'
  json_number: '#ea9d34'
  json_string: '#ea9d34'
  json_boolean: '#d7827e'
  json_null: '#b4637a'
method:
  get: 'bold #907aa9'
  post: 'bold #56949f'
  put: 'bold #ea9d34'
  delete: 'bold #b4637a'
  patch: 'bold #286983'
  head: 'bold #d7827e'
  options: 'bold #575279'
variable:
  resolved: 'bold #575279'
  unresolved: 'dim #575279'

author: Michael Howard
description: All natural pine, faux fur and a bit of soho vibes for the classy minimalist
homepage: https://github.com/elithper/posting
```
