### ISSUE TITLE
Name or service unknown

### ISSUE THREAD

**Issue by CaptainQuirk** [darrenburns/posting#208]
Hi !

I'm facing a weird issue using posting.

## Environment

I'm using the 2.4.0 version, installed with uv, with python 3.12, on a Ubuntu 22.04 WSL 

## Setup 

My routes definitions and environment file are located in a `.posting` directory which is itself a symlink to a `~/Posting/myapi` directory.

It has the following structure : 

```
.posting
├── .env.dev
└── v1
    └── auth
        └── v1-auth-token.posting.yaml
```

My route definition looks like this : 

```yaml
name: /v1/auth/token
description: |-
  Génère un Json Web Token à partir d'un clientId et d'un clientSecret.
method: POST
url: $BASE_URL/v1/auth/token
body:
  content: |-
    {
      "clientId": "local",
      "clientSecret": "secret"
    }
  content_type: application/json
headers:
- name: Accept
  value: application/json
- name: Content-Type
  value: application/json
```

## Steps

I'm launching posting with the following command  : 

```console
posting --collection .posting --env .posting/.env.dev
```

## Expected result

I expect the call to succeed.
I add that : 

- Other instances of posting pointing to other collections and env files work fine
- The variable `$BASE_URL` gets autocompleted in posting and its value seem to be resolved correctly as it appears below the URL field
- The route I'm trying to call exists and works (direct curl call in the terminal or a web based swagger UI)

## Actual result

The request does not seem to be executed and I get a message telling :

> Couldn't send request
> [Errno -2] Name or service not known

## Screenshots

![Image](https://github.com/user-attachments/assets/df746643-8d3e-44b6-9251-04aae929aa53)
