### ISSUE TITLE
Can't define query parameters as an array of objects

### ISSUE THREAD

**Issue by diegotoral** [darrenburns/posting#235]
I am working with an API where some endpoints expect a very specific and unusual format for query parameters. I believe this format is not currently supported on posting 2.5.4 as I was unable to get it working through the query editor nor by manually editing the request YAML file.

The request is as follows:

```
/api/invites?filters%5B%5D%5Bid%5D%3D1%26filters%5B%5D%5Bvalue%5D%3Dabc%26filters%5B%5D%5Bid%5D%3D2%26filters%5B%5D%5Bvalue%5D%3Dcba
```

or more clearly

```
/api/invites?filters[][id]=1&filters[][value]=abc&filters[][id]=2&filters[][value]=cba
```

This gets translated to the following structure when parsed in the API

```
{ filters: [{ id: 1, value: "abc" }, { id: 2, value: "cba" }] }
```

Which I translated to YAML as

```yaml
params:
  - name: flex_definitions:
    value:
      - id: 1
        value: 2
      - id: 3
        value: 4
```

This is the error I get when loading posting

```
Failed to load invites.posting.yaml: 1 validation error for RequestModel
params.0.value
  Input should be a valid string [type=string_type, input_value=[{'id': 24, 'value': 'a'}...6, 'value': 'option 3'}], input_type=list]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
```

**Comment by darrenburns** [comment]
Can you clarify exactly what it is you're doing in the Posting UI?

From your description, I can't work out what you're typing and where, and can't reproduce the error.

**Comment by diegotoral** [comment]
Sorry about that.

The issue is that I can't make Posting work with a collection file where query parameters are formatted as below:

```
params:
  - name: flex_definitions:
    value:
      - id: 1
        value: 2
      - id: 3
        value: 4
```

Posting fails with a validation error `Failed to load invites.posting.yaml: 1 validation error for RequestModel` when loading the file.
