### ISSUE TITLE
Support for encrypting/decrypting passwords for BasicAuth

### ISSUE THREAD

**Issue by sczsh** [darrenburns/posting#80]
Hi,

I'd like to propose a feature, which lets the user set a master password via ENV variable, which is then used to encrypt/decrypt the password field in the *.posting.yaml file

Current situation for a *.posting.yaml file

```
name: Get Player 
description: Gets a player by id
url: https://localhost:8080/player/4
auth:
  type: basic
  basic:
    username: test
    password: test
headers:
- name: Content-Type
  value: application/json
```

Proposed change:

```
name: Get Player
description: Gets a player by id
url: https://localhost:8080/player/4
auth:
  type: basic
  basic:
    username: test
    enc_password: U2FsdGVkX18UCL1XW/Xxg7oyj7sBlg8p0ot+f3rW6Lc=
headers:
- name: Content-Type
  value: application/json
```

The example "enc_password" was generated with

`echo "test" | openssl enc -e -aes-256-cbc -a -salt -pbkdf2`

and "123456" as password.

Reason for this proposal:

Encrypting the BasicAuth credentials would it make easier to share a larger number of collections safely, for example, via VCS without the possibility to accidentaly push the plaintext password. Also then there would be no need to remove the plaintext credentials, before pushing such a collection (or more collections), by hand and have to type
them in again after i cloned the repo.

The following steps show how this could work in the application:

* Set ENV variable POSTING_MASTER_PASSWORD=123456
* Start posting and load collection by "posting --collection myCollection"
** Decrypt the password field with POSTING_MASTER_PASSWORD and set the plaintext password together with the username in the "Auth" tab
* Save collection
** Encrypt the value of the password field with POSTING_MASTER_PASSWORD and write it back to the *.posting.yaml file

If the ENV variable is not set, the default behaveior (no encryption/decryption) will be activated

Thanks for this awesome tool and best regards
